### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by sigorilla** [banditi/joinme-android-app#1]
Hi, @banditi/codebusters 
Discuss here our ideas.
As you add ideas I will fill up the list in this issue.
## Ideas
- [x] Android App
- [x] Web-service
- [x] Events application

**Comment by sigorilla** [comment]
## Events application

Web and Android app with different information about the future events on MIPT.

**Comment by krokhin** [comment]
## Events application

Web-service for MIPT's students' leisure managment (e.g. all interest groups, such as English club or different types of events organised by 'profkom'): DB with all inforamation + site with api + simple android client

**Comment by sigorilla** [comment]
## Material design for our project!

On the site we can use themes like these: [Material Design for Bootstrap](http://fezvrasta.github.io/bootstrap-material-design/)

How use material design on Android you can read on [Habr](http://habrahabr.ru/company/surfingbird/blog/244387/)
