### ISSUE TITLE
Registration Form

### ISSUE THREAD

**Issue by sigorilla** [banditi/joinme-android-app#2]
# Discuss Name of our Team

And other fields of [the form](https://skoltechhackathon.timepad.ru/event/196394/).
## Name
- [x] `CodeBusters`
## Members

```
Igor Stepanov
Efim Krokhin
Vadim Varnavsky
Egor Kuznetsov
```
## Interests

`IT, Android, WEB`

**Comment by petya0** [comment]
CodeBusters

**Comment by krokhin** [comment]
CodeBusters

**Comment by sigorilla** [comment]
Thank you, @Yefim-Krokhin. I think it's good name :+1: 
If nothing will found, we can use this name.

**Comment by sigorilla** [comment]
OK. I think it's final name for our project. 
I close this issue.

**Comment by Nipel-Crumple** [comment]
Could it be more convenient to write our names in English to not break this 'english' style?

**Comment by Nipel-Crumple** [comment]
Done! Sorry If someone's name is wrong. Fix it if you want.
